import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const categoriesData = [
  {
    name: 'Men',
    slug: 'men',
    description: 'Contemporary menswear featuring premium Panjabis, shirts, polos, and denim.',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=800&auto=format&fit=crop&q=80',
  },
  {
    name: 'Women',
    slug: 'women',
    description: 'Elegant womenswear including traditional sarees, three pieces, kurtis, and chic dresses.',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
  },
  {
    name: 'Kids',
    slug: 'kids',
    description: 'Playful, comfortable, and durable apparel for boys and girls.',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop&q=80',
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Refined leather goods, chronograph watches, bags, and daily essentials.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
  },
];

const productsData = [
  // ==================== MEN (12 Products) ====================
  {
    name: 'Classic Jacquard Cotton Panjabi',
    slug: 'classic-jacquard-cotton-panjabi',
    description: 'Tailored from breathable 100% combed cotton jacquard fabric with delicate embroidery on the mandarin collar and placket. Perfect for Eid and festive gatherings.',
    price: 2690,
    discountPrice: 2290,
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Panjabi',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Navy Blue', 'Maroon'],
    rating: 4.8,
    reviewsCount: 34,
    stock: 45,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Royal Embroidered Silk Blend Panjabi',
    slug: 'royal-embroidered-silk-blend-panjabi',
    description: 'Luxurious silk blend semi-fitted Panjabi accented with metallic thread zari hand embroidery along the neckline.',
    price: 3890,
    discountPrice: 3290,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Panjabi',
    sizes: ['M', 'L', 'XL'],
    colors: ['Emerald Green', 'Charcoal Black', 'Deep Gold'],
    rating: 4.9,
    reviewsCount: 22,
    stock: 28,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: 'Breathable Pure Linen Casual Shirt',
    slug: 'breathable-pure-linen-casual-shirt',
    description: 'Made from premium pre-washed European flax linen. Keeps you exceptionally cool and stylish throughout the humid tropical summer.',
    price: 1990,
    discountPrice: 1690,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sky Blue', 'Beige', 'White'],
    rating: 4.7,
    reviewsCount: 19,
    stock: 60,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'Oxford Button-Down Formal Shirt',
    slug: 'oxford-button-down-formal-shirt',
    description: 'Heavyweight pin-point Oxford cotton with a structured collar. A sharp, timeless staple for corporate and business meetings.',
    price: 1850,
    discountPrice: 1550,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Shirt',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Crisp White', 'Soft Pink', 'Light Blue'],
    rating: 4.6,
    reviewsCount: 42,
    stock: 55,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Modern Pique Cotton Polo Shirt',
    slug: 'modern-pique-cotton-polo-shirt',
    description: 'Crafted with 240 GSM double-pique cotton. Features tipping details on rib-knit collar and mother-of-pearl buttons.',
    price: 1290,
    discountPrice: 990,
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Polo',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Burgundy', 'Forest Green', 'Black'],
    rating: 4.5,
    reviewsCount: 50,
    stock: 75,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Vintage Wash Slim Tapered Jeans',
    slug: 'vintage-wash-slim-tapered-jeans',
    description: 'Durable 12.5 oz stretch indigo denim with authentic whiskers and hand-sanded fading. Designed with a comfortable mid-rise cut.',
    price: 2490,
    discountPrice: 1990,
    image: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Jeans',
    sizes: ['30', '32', '34', '36'],
    colors: ['Vintage Blue', 'Deep Indigo'],
    rating: 4.6,
    reviewsCount: 38,
    stock: 40,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Smart Stretch Chino Trousers',
    slug: 'smart-stretch-chino-trousers',
    description: 'Versatile cotton-twill chinos engineered with 3% elastane for effortless mobility. Looks equally polished with loafers or sneakers.',
    price: 1950,
    discountPrice: 1650,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Pant',
    sizes: ['30', '32', '34', '36'],
    colors: ['Khaki', 'Olive Green', 'Charcoal'],
    rating: 4.7,
    reviewsCount: 26,
    stock: 50,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'Heavyweight Drop-Shoulder Oversized Tee',
    slug: 'heavyweight-drop-shoulder-oversized-tee',
    description: 'Streetwear-inspired relaxed fit cut from 260 GSM organic combed cotton with a high crew neckline that holds its shape.',
    price: 990,
    discountPrice: 790,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'T-Shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Off-White', 'Washed Black', 'Sage Green'],
    rating: 4.8,
    reviewsCount: 65,
    stock: 80,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: 'Premium Pima Cotton Crewneck Tee',
    slug: 'premium-pima-cotton-crewneck-tee',
    description: 'Ultra-soft Peruvian pima cotton basic t-shirt with silk-like finish and reinforced shoulder taping for zero sagging.',
    price: 850,
    discountPrice: 690,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'T-Shirt',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Navy', 'Heather Grey'],
    rating: 4.4,
    reviewsCount: 30,
    stock: 90,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Printed Cuban Collar Resort Shirt',
    slug: 'printed-cuban-collar-resort-shirt',
    description: 'Lighweight viscose shirt featuring botanical micro-prints, a relaxed open notch collar, and a straight hem.',
    price: 1690,
    discountPrice: 1390,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Shirt',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Monochrome Palm', 'Terracotta Geo'],
    rating: 4.6,
    reviewsCount: 14,
    stock: 35,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'Relaxed Tapered Utility Cargo Pants',
    slug: 'relaxed-tapered-utility-cargo-pants',
    description: 'Rugged cotton ripstop cargo pants with 6 tactical pockets, articulated knees, and an elasticated drawstring waistband.',
    price: 2290,
    discountPrice: 1890,
    image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Pant',
    sizes: ['30', '32', '34', '36'],
    colors: ['Military Green', 'Midnight Black'],
    rating: 4.7,
    reviewsCount: 20,
    stock: 35,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Fine Cotton Contrast Collar Polo',
    slug: 'fine-cotton-contrast-collar-polo',
    description: 'Smart-casual polo with contrast jacquard collar and sleeve bands. Enzyme treated for extreme softness and lint resistance.',
    price: 1390,
    discountPrice: 1090,
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'men',
    subCategory: 'Polo',
    sizes: ['M', 'L', 'XL'],
    colors: ['Teal', 'Crimson Red', 'Royal Blue'],
    rating: 4.5,
    reviewsCount: 17,
    stock: 40,
    isTrending: false,
    isNewArrival: false,
  },

  // ==================== WOMEN (12 Products) ====================
  {
    name: 'Handwoven Dhakai Jamdani Saree',
    slug: 'handwoven-dhakai-jamdani-saree',
    description: 'Exquisite 100 count cotton Dhakai Jamdani woven on traditional pit looms with intricate floral motifs throughout the body and aanchal.',
    price: 6500,
    discountPrice: 5490,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Saree',
    sizes: ['Free Size'],
    colors: ['Royal Red', 'Ivory Gold', 'Midnight Blue'],
    rating: 4.9,
    reviewsCount: 45,
    stock: 20,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: 'Embroidered Georgette Party Saree',
    slug: 'embroidered-georgette-party-saree',
    description: 'Fluid lightweight georgette drape accented with dual-tone sequin borders and matching unstitched blouse fabric.',
    price: 4490,
    discountPrice: 3890,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Saree',
    sizes: ['Free Size'],
    colors: ['Blush Pink', 'Plum Purple', 'Teal'],
    rating: 4.8,
    reviewsCount: 29,
    stock: 25,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Digital Printed Lawn Three Piece',
    slug: 'digital-printed-lawn-three-piece',
    description: 'Premium unstitched 3-piece set with a high-definition printed lawn kameez, matching dyed cotton trousers, and a soft chiffon dupatta.',
    price: 2890,
    discountPrice: 2450,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Three Piece',
    sizes: ['Unstitched', 'Stitched M', 'Stitched L'],
    colors: ['Pastel Mint', 'Coral Peach', 'Mustard Yellow'],
    rating: 4.7,
    reviewsCount: 38,
    stock: 50,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: 'Festive Embroidered Silk Three Piece',
    slug: 'festive-embroidered-silk-three-piece',
    description: 'Chanderi silk festive ensemble embroidered with resham threadwork, paired with cigarette pants and an organza dupatta with lace trim.',
    price: 4950,
    discountPrice: 4190,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Three Piece',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Emerald', 'Ruby Red', 'Deep Navy'],
    rating: 4.9,
    reviewsCount: 21,
    stock: 30,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'A-Line Block Printed Cotton Kurti',
    slug: 'a-line-block-printed-cotton-kurti',
    description: 'Flattering A-line silhouette with authentic wooden block print motifs, front slit, and tassel details on the keyhole neckline.',
    price: 1650,
    discountPrice: 1290,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Kurti',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Indigo', 'Maroon', 'Beige'],
    rating: 4.6,
    reviewsCount: 52,
    stock: 65,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Floral Embroidered Rayon Short Kurti',
    slug: 'floral-embroidered-rayon-short-kurti',
    description: 'Trendy short tunic length kurti crafted from soft modal rayon with pastel floral thread embroidery on the yoke.',
    price: 1390,
    discountPrice: 1150,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Kurti',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Lavender', 'Powder Blue', 'White'],
    rating: 4.5,
    reviewsCount: 31,
    stock: 55,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'Tiered Floral Bohemian Maxi Dress',
    slug: 'tiered-floral-bohemian-maxi-dress',
    description: 'Flowing tiered bohemian maxi dress featuring ditsy meadow prints, puff sleeves, and a smocked elastic bodice for a flattering fit.',
    price: 2450,
    discountPrice: 1950,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Dress',
    sizes: ['S', 'M', 'L'],
    colors: ['Floral Sage', 'Dusty Rose'],
    rating: 4.8,
    reviewsCount: 40,
    stock: 35,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: 'Minimalist Linen Wrap Midi Dress',
    slug: 'minimalist-linen-wrap-midi-dress',
    description: 'Clean modern wrap dress with a V-neckline, self-tie sash at the waist, and hidden side pockets. Pure summer sophistication.',
    price: 2790,
    discountPrice: 2290,
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Dress',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Oatmeal', 'Olive', 'Terracotta'],
    rating: 4.7,
    reviewsCount: 18,
    stock: 25,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Chic Chiffon Ruffle Wrap Top',
    slug: 'chic-chiffon-ruffle-wrap-top',
    description: 'Double-layered semi-sheer chiffon wrap top with delicate frill trim along the neckline and bell sleeves.',
    price: 1250,
    discountPrice: 990,
    image: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Tops',
    sizes: ['S', 'M', 'L'],
    colors: ['Wine Red', 'Jet Black', 'Cream'],
    rating: 4.6,
    reviewsCount: 24,
    stock: 45,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Peplum Buttoned Cotton Blouse',
    slug: 'peplum-buttoned-cotton-blouse',
    description: 'Structured cotton blouse with a cinched peplum waist, tonal wooden buttons, and a sweetheart neckline.',
    price: 1190,
    discountPrice: 950,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Mustard', 'White', 'Charcoal'],
    rating: 4.4,
    reviewsCount: 16,
    stock: 40,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'Traditional Half-Silk Tangail Saree',
    slug: 'traditional-half-silk-tangail-saree',
    description: 'Authentic Tangail weave half-silk saree with lustrous finish, gold zari borders, and contrasting color pallu.',
    price: 3490,
    discountPrice: 2990,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Saree',
    sizes: ['Free Size'],
    colors: ['Sunshine Yellow', 'Magenta Pink', 'Parrot Green'],
    rating: 4.7,
    reviewsCount: 33,
    stock: 30,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Embroidered Long Cotton Kurti',
    slug: 'embroidered-long-cotton-kurti',
    description: 'Straight-cut long kurti in 100% fine cotton featuring intricate kashmiri thread embroidery around the placket and cuffs.',
    price: 1890,
    discountPrice: 1490,
    image: 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'women',
    subCategory: 'Kurti',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Deep Teal', 'Crimson', 'Charcoal'],
    rating: 4.8,
    reviewsCount: 27,
    stock: 50,
    isTrending: true,
    isNewArrival: false,
  },

  // ==================== KIDS (8 Products) ====================
  {
    name: "Boys' Festive Cotton Panjabi & Pajama Set",
    slug: 'boys-festive-cotton-panjabi-set',
    description: 'Charming festive outfit for boys made with breathable cotton, subtle neckline embroidery, and matching comfortable elasticized pajama.',
    price: 1690,
    discountPrice: 1390,
    image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Boys',
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs', '10-11 Yrs'],
    colors: ['Royal Blue', 'Ivory Cream', 'Maroon'],
    rating: 4.9,
    reviewsCount: 36,
    stock: 45,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: "Boys' Striped Polo Shirt",
    slug: 'boys-striped-polo-shirt',
    description: '100% soft cotton pique polo with yarn-dyed horizontal stripes and gentle collar ribbing that resists stretching.',
    price: 790,
    discountPrice: 590,
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Kids T-Shirt',
    sizes: ['3-4 Yrs', '5-6 Yrs', '7-8 Yrs', '9-10 Yrs'],
    colors: ['Navy & White', 'Red & Navy', 'Yellow & Grey'],
    rating: 4.6,
    reviewsCount: 22,
    stock: 60,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: "Boys' Dinosaur Adventure Graphic Tee",
    slug: 'boys-dinosaur-adventure-graphic-tee',
    description: 'Fun, color-fast screen printed cotton t-shirt with whimsical cartoon illustrations. Machine washable and shrink-resistant.',
    price: 550,
    discountPrice: 420,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Kids T-Shirt',
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs'],
    colors: ['Lemon Yellow', 'Sky Blue', 'White'],
    rating: 4.7,
    reviewsCount: 40,
    stock: 70,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: "Boys' Elastic Waist Stretch Chino Shorts",
    slug: 'boys-elastic-waist-stretch-chino-shorts',
    description: 'Comfortable playground-ready cotton twill shorts with an adjustable drawstring waist and deep side pockets.',
    price: 890,
    discountPrice: 690,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Boys',
    sizes: ['3-4 Yrs', '5-6 Yrs', '7-8 Yrs', '9-10 Yrs'],
    colors: ['Khaki', 'Navy', 'Olive'],
    rating: 4.5,
    reviewsCount: 15,
    stock: 50,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: "Girls' Embroidered Party Frock",
    slug: 'girls-embroidered-party-frock',
    description: 'Gorgeous layered net and satin party frock with hand-stitched floral bodice, satin ribbon sash, and cotton inner lining for sensitive skin.',
    price: 1950,
    discountPrice: 1590,
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Girls',
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs'],
    colors: ['Pastel Pink', 'Lavender', 'Peach'],
    rating: 4.9,
    reviewsCount: 33,
    stock: 35,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: "Girls' Tiered Summer Floral Cotton Dress",
    slug: 'girls-tiered-summer-floral-cotton-dress',
    description: 'Bright and breezy floral printed cotton A-line dress with flutter sleeves and a gentle gathered hem.',
    price: 1150,
    discountPrice: 890,
    image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Kids Dress',
    sizes: ['3-4 Yrs', '5-6 Yrs', '7-8 Yrs', '9-10 Yrs'],
    colors: ['Daisy Yellow', 'Rose Pink'],
    rating: 4.8,
    reviewsCount: 28,
    stock: 40,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: "Girls' Traditional Cotton Kurti & Tulip Pants",
    slug: 'girls-traditional-cotton-kurti-tulip-pants',
    description: 'Festive 2-piece outfit featuring a printed cotton kurti paired with soft tulip shalwar pants.',
    price: 1490,
    discountPrice: 1190,
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Girls',
    sizes: ['4-5 Yrs', '6-7 Yrs', '8-9 Yrs', '10-11 Yrs'],
    colors: ['Ruby Red', 'Teal Green'],
    rating: 4.7,
    reviewsCount: 19,
    stock: 30,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: "Girls' Unicorn Rainbow Printed Tee",
    slug: 'girls-unicorn-rainbow-printed-tee',
    description: 'Playful rainbow foil glitter t-shirt made of 100% hypoallergenic organic cotton jersey.',
    price: 590,
    discountPrice: 450,
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'kids',
    subCategory: 'Kids T-Shirt',
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs'],
    colors: ['Baby Pink', 'Lilac', 'White'],
    rating: 4.6,
    reviewsCount: 25,
    stock: 65,
    isTrending: false,
    isNewArrival: false,
  },

  // ==================== ACCESSORIES (8 Products) ====================
  {
    name: 'Full Grain Leather Executive Messenger Bag',
    slug: 'full-grain-leather-executive-messenger-bag',
    description: 'Handcrafted from vegetable-tanned cowhide leather. Fits up to 15.6" laptops, with dedicated tablet and document sleeves and brass hardware.',
    price: 4950,
    discountPrice: 4150,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Bag',
    sizes: ['One Size'],
    colors: ['Cognac Tan', 'Dark Espresso', 'Classic Black'],
    rating: 4.9,
    reviewsCount: 48,
    stock: 25,
    isTrending: true,
    isNewArrival: true,
  },
  {
    name: "Women's Structured Saffiano Leather Tote",
    slug: 'womens-structured-saffiano-leather-tote',
    description: 'Spacious everyday tote with scratch-resistant Saffiano finish, zipper top closure, and protective bottom metal studs.',
    price: 3690,
    discountPrice: 2990,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Bag',
    sizes: ['One Size'],
    colors: ['Blush Pink', 'Taupe', 'Onyx Black'],
    rating: 4.8,
    reviewsCount: 37,
    stock: 30,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Chronograph Matte Black Stainless Steel Watch',
    slug: 'chronograph-matte-black-watch',
    description: 'Precision Japanese quartz movement chronograph featuring 50m water resistance, date display, and an interchangeable mesh band.',
    price: 3290,
    discountPrice: 2750,
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Watch',
    sizes: ['42mm'],
    colors: ['Matte Black', 'Silver & Blue', 'Gunmetal'],
    rating: 4.7,
    reviewsCount: 54,
    stock: 40,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Minimalist Classic White Dial Leather Watch',
    slug: 'minimalist-classic-leather-watch',
    description: 'Ultra-slim 7mm watch case with clean Roman numerals, scratch-resistant sapphire crystal glass, and genuine brown leather strap.',
    price: 2490,
    discountPrice: 1990,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Watch',
    sizes: ['40mm'],
    colors: ['Rose Gold & Tan', 'Silver & Black'],
    rating: 4.6,
    reviewsCount: 29,
    stock: 35,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'RFID-Blocking Leather Bi-Fold Wallet',
    slug: 'rfid-blocking-leather-bifold-wallet',
    description: 'Slim top-grain leather wallet equipped with RFID shield lining, 8 card slots, 2 currency compartments, and an ID window.',
    price: 1290,
    discountPrice: 990,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Wallet',
    sizes: ['Standard'],
    colors: ['Rich Tan', 'Midnight Black', 'Vintage Brown'],
    rating: 4.8,
    reviewsCount: 62,
    stock: 80,
    isTrending: true,
    isNewArrival: false,
  },
  {
    name: 'Reversible Italian Full-Grain Leather Belt',
    slug: 'reversible-italian-leather-belt',
    description: '35mm wide versatile belt with a rotating brushed chrome buckle. Switch effortlessly between black and dark brown sides.',
    price: 1450,
    discountPrice: 1190,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Belt',
    sizes: ['32', '34', '36', '38', '40'],
    colors: ['Black/Brown Reversible'],
    rating: 4.7,
    reviewsCount: 41,
    stock: 60,
    isTrending: false,
    isNewArrival: false,
  },
  {
    name: 'Classic Polarized Aviator Sunglasses',
    slug: 'classic-polarized-aviator-sunglasses',
    description: 'Timeless teardrop frame with UV400 polarized TAC lenses that eliminate glare and provide optimal clarity in strong sun.',
    price: 1850,
    discountPrice: 1450,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Sunglasses',
    sizes: ['Standard'],
    colors: ['Gold Frame / Green Lens', 'Black Frame / Dark Grey Lens'],
    rating: 4.7,
    reviewsCount: 30,
    stock: 45,
    isTrending: false,
    isNewArrival: true,
  },
  {
    name: 'Water-Resistant Urban Travel Backpack',
    slug: 'water-resistant-urban-travel-backpack',
    description: 'Sleek waterproof Oxford fabric backpack with hidden anti-theft back pocket, luggage trolley strap, and padded 16" laptop compartment.',
    price: 2690,
    discountPrice: 2190,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    categorySlug: 'accessories',
    subCategory: 'Bag',
    sizes: ['22 Liters'],
    colors: ['Charcoal Heather', 'Jet Black', 'Navy'],
    rating: 4.8,
    reviewsCount: 39,
    stock: 50,
    isTrending: true,
    isNewArrival: false,
  },
];

async function main() {
  console.log('Seeding categories and products...');

  // Upsert categories
  const categoryMap = {};
  for (const cat of categoriesData) {
    const category = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
    categoryMap[cat.slug] = category.id;
    console.log(`✓ Category: ${category.name}`);
  }

  // Upsert products
  let count = 0;
  for (const prod of productsData) {
    const { categorySlug, ...rest } = prod;
    const categoryId = categoryMap[categorySlug];
    if (!categoryId) {
      console.warn(`Category not found for slug: ${categorySlug}`);
      continue;
    }

    await prisma.product.upsert({
      where: { slug: rest.slug },
      update: {
        ...rest,
        categoryId,
      },
      create: {
        ...rest,
        categoryId,
      },
    });
    count++;
  }

  console.log(`✓ Successfully seeded ${count} products across all categories.`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
